// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: coloring_info.proto

package app
import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoroingService_GetColoringInfo_FullMethodName = "/app.CoroingService/GetColoringInfo"
)

// CoroingServiceClient is the client API for CoroingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoroingServiceClient interface {
	GetColoringInfo(ctx context.Context, in *ServerRequest, opts ...grpc.CallOption) (*ServerReply, error)
}

type coroingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoroingServiceClient(cc grpc.ClientConnInterface) CoroingServiceClient {
	return &coroingServiceClient{cc}
}

func (c *coroingServiceClient) GetColoringInfo(ctx context.Context, in *ServerRequest, opts ...grpc.CallOption) (*ServerReply, error) {
	out := new(ServerReply)
	err := c.cc.Invoke(ctx, CoroingService_GetColoringInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoroingServiceServer is the server API for CoroingService service.
// All implementations must embed UnimplementedCoroingServiceServer
// for forward compatibility
type CoroingServiceServer interface {
	GetColoringInfo(context.Context, *ServerRequest) (*ServerReply, error)
	mustEmbedUnimplementedCoroingServiceServer()
}

// UnimplementedCoroingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCoroingServiceServer struct {
}

func (UnimplementedCoroingServiceServer) GetColoringInfo(context.Context, *ServerRequest) (*ServerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetColoringInfo not implemented")
}
func (UnimplementedCoroingServiceServer) mustEmbedUnimplementedCoroingServiceServer() {}

// UnsafeCoroingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoroingServiceServer will
// result in compilation errors.
type UnsafeCoroingServiceServer interface {
	mustEmbedUnimplementedCoroingServiceServer()
}

func RegisterCoroingServiceServer(s grpc.ServiceRegistrar, srv CoroingServiceServer) {
	s.RegisterService(&CoroingService_ServiceDesc, srv)
}

func _CoroingService_GetColoringInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoroingServiceServer).GetColoringInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoroingService_GetColoringInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoroingServiceServer).GetColoringInfo(ctx, req.(*ServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoroingService_ServiceDesc is the grpc.ServiceDesc for CoroingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoroingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.CoroingService",
	HandlerType: (*CoroingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetColoringInfo",
			Handler:    _CoroingService_GetColoringInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coloring_info.proto",
}
